
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_FORMS = "FETCH_FORMS";
export const FETCH_SINGLE_FORM = "FETCH_SINGLE_FORM";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";